### ISSUE TITLE
Krita crashes on startup

### ISSUE THREAD

**Issue by joeky888** [linuxdeepin/qt5integration#35]
Coming from https://github.com/linuxdeepin/developer-center/issues/1982

I am using Manjaro testing branch.

Execute:

```python
$ krita
[1]    43604 segmentation fault (core dumped)  krita
```

Stack trace:

```cpp
(gdb) bt full
#0  0x00007fffef105b1a in deepin_platform_plugin::DHighDpi::logicalDpi(QXcbScreen*) () at /usr/lib/qt/plugins/platforms/libdxcb.so
#1  0x00007ffff4f6f542 in  () at /usr/lib/libQt5Gui.so.5
#2  0x00007ffff4f1d9e3 in QWindowSystemInterface::handleScreenAdded(QPlatformScreen*, bool) () at /usr/lib/libQt5Gui.so.5
#3  0x00007fffeefe66a1 in QXcbConnection::initializeScreens() () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007fffeefc1338 in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) () at /usr/lib/libQt5XcbQpa.so.5
#5  0x00007fffeefc40f5 in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) () at /usr/lib/libQt5XcbQpa.so.5
#6  0x00007fffef0ff8b1 in deepin_platform_plugin::DPlatformIntegration::DPlatformIntegration(QStringList const&, int&, char**) ()
    at /usr/lib/qt/plugins/platforms/libdxcb.so
#7  0x00007fffef0fefc7 in DPlatformIntegrationPlugin::create(QString const&, QStringList const&, int&, char**) ()
    at /usr/lib/qt/plugins/platforms/libdxcb.so
#8  0x00007ffff4f3c627 in QGuiApplicationPrivate::createPlatformIntegration() () at /usr/lib/libQt5Gui.so.5
#9  0x00007ffff4f3dae1 in QGuiApplicationPrivate::createEventDispatcher() () at /usr/lib/libQt5Gui.so.5
#10 0x00007ffff4b74936 in QCoreApplicationPrivate::init() () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff4f40b20 in QGuiApplicationPrivate::init() () at /usr/lib/libQt5Gui.so.5
#12 0x00007ffff4f41a88 in QGuiApplication::QGuiApplication(int&, char**, int) () at /usr/lib/libQt5Gui.so.5
#13 0x00007ffff6f6f074 in KisOpenGLModeProber::probeFormat(KisOpenGL::RendererConfig const&, bool) () at /usr/lib/libkritaui.so.20
#14 0x00007ffff6f5702c in KisOpenGL::selectSurfaceConfig(KisOpenGL::OpenGLRenderer, KisConfig::RootSurfaceFormat, bool) ()
    at /usr/lib/libkritaui.so.20
#15 0x0000555555e26e2d in main ()
```

**Comment by moham96** [comment]
same problem here.
I'm on manjaro stable

**Comment by kegechen** [comment]
dde-qt5xcb-plugin >= 5.0.24 may be fixed..  
memprotect(xxx--xxx) //readonly
new obj on xxx--xxx
crashed

**Comment by BLumia** [comment]
Now we are on 5.5.23 and Krita no longer crashes in the most recent release on current Arch Linux with DDE or on deepin, so I guess we can close this one for now. If that still happens, please feel free to open a new issue so we can look into it. Thanks!
